[package]
name = "nth-tui"
version.workspace = true
edition.workspace = true

[dependencies]
nth-context.workspace = true
nth-format.workspace = true
nth-lsp.workspace = true
nth-protocol.workspace = true
nth-session.workspace = true
anyhow.workspace = true
braille-bar.workspace = true
crossterm.workspace = true
futures.workspace = true
hoodrich.workspace = true
ignore.workspace = true
nucleo-matcher.workspace = true
ratatui.workspace = true
serde_json.workspace = true
similar.workspace = true
textwrap.workspace = true
tokio.workspace = true
unicode-width.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
