[package]
name = "nth-tui"
version.workspace = true
edition.workspace = true

[dependencies]
nth-protocol.workspace = true
nth-session.workspace = true
anyhow.workspace = true
crossterm.workspace = true
futures.workspace = true
ratatui.workspace = true
textwrap.workspace = true
tokio.workspace = true
unicode-width.workspace = true
