[package]
name = "nth-tools"
version.workspace = true
edition.workspace = true

[dependencies]
nth-context.workspace = true
nth-protocol.workspace = true
futures.workspace = true
htmd.workspace = true
ignore.workspace = true
libc.workspace = true
regex.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["net"] }
